#use_frameworks!

platform :ios, '8.0'

target 'ZYCommonSDK_Example' do
  pod 'ZYCommonSDK', :path => '../'

  target 'ZYCommonSDK_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
